apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  selector:
      matchLabels:
        app: eureka-server
  replicas: 3
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eurekaserver
          image: omrmtn/eurekaserver:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080