version: "3"
services:
  eurekaserver:
    image: omrmtn/eurekaserver:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks:
      - my-eureka-network

  studentservice:
    image: omrmtn/studentservice:0.0.1-SNAPSHOT
    ports:
      - "8014:8014"
    depends_on:
      - eurekaserver
    networks:
      - my-eureka-network

  schoolservice:
    image: omrmtn/schoolservice:0.0.1-SNAPSHOT
    ports:
      - "8015:8015"
    depends_on:
      - eurekaserver
      - studentservice
    networks:
      - my-eureka-network

networks:
  my-eureka-network:
