version: "3"
services:
  eureka-server:
    image: eureka-server
    ports:
      - "8761:8761"
    networks:
      - my-eureka-network

  student-service:
    image: student-service
    ports:
      - "8014:8014"
    depends_on:
      - eureka-server
    networks:
      - my-eureka-network

  school-service:
    image: school-service
    ports:
      - "8015:8015"
    depends_on:
      - eureka-server
      - student-service
    networks:
      - my-eureka-network

networks:
  my-eureka-network:
