server:
  port: 8015    
  
spring:    
  application:
    name: schoolservice      
 
eureka:         
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
logging:
  level:
    com.self.sprintboot.learning.employee: DEBUG