apiVersion: apps/v1
kind: Deployment
metadata: 
  name: schoolservicedeployment
spec:
  selector:
      matchLabels:
        app: schoolservice
  replicas: 3
  template:
    metadata:
      labels:
        app: schoolservice
    spec:
      containers:
        - name: schoolservice
          image: omrmtn/schoolservice:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080