server:
  port: 8761
# port: ${PORT:8761}
 
spring:    
  application:
    name: _01_eureka-server       
  boot:
    admin:
      context-path: /admin  #A different context path for admin server has been provided not conflicting with eureka
       
eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
 
#management:
#  security:
#    enabled: false